version: '3'

services:
  receiver:
    build: .
    command: app/smartDentistBroker/script.sh
    ports:
      - "56789:56789"
    volumes:
      - .:/code

  forn1:
    build: .
    command: python3 app/smartDentistForno/smartDentistForno.py 10
    volumes:
      - .:/code