version: '3'

services:
  msg_broker:
    image: rabbitmq

  broker:
    build: .
    command: python3 app/smartDentistBroker/smartDentistBroker.py
    volumes:
      - .:/code
    depends_on:
      - msg_broker

  forn1:
    build: .
    command: python3 app/smartDentistForno/smartDentistForno.py 10
    volumes:
      - .:/code
    depends_on:
      - msg_broker

  forn2:
    build: .
    command: python3 app/smartDentistForno/smartDentistForno.py 15
    volumes:
      - .:/code
    depends_on:
      - msg_broker

  forn3:
    build: .
    command: python3 app/smartDentistForno/smartDentistForno.py 17
    volumes:
      - .:/code
    depends_on:
      - msg_broker