version: '3'

services:
  db_postgres:
    image: postgres
  web:
    build: .
    command: python3 app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
      - logstash
# index, search & agregation
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elastic
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - "esdata:/usr/share/elasticsearch/data"
    networks:
      - logging
# UI
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./elk/kibana/config/kibana.yml:/etc/kibana/kibana.yml
    networks:
      - logging
    depends_on:
      - elasticsearch
# indexer
  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    container_name: logstash
    command: logstash -f /config/
    environment:
      - LS_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
     - 5959:5959
    volumes:
      - ./elk/logstash/config:/config
    networks:
      - logging
    depends_on:
      - elasticsearch
#server
  # apmserver:
  #   image: docker.elastic.co/apm/apm-server:6.2.4
  #   container_name: apmserver
  #   command: chmod go-w /usr/share/apm-server/apm-server.yml
  #   ports:
  #     - 8200:8200
  #   volumes:
  #     - ./elk/apmserver/config/apm-server.yml:/usr/share/apm-server/apm-server.yml
  #   networks:
  #     - logging
  #   depends_on:
  #     - elasticsearch

volumes:
  esdata:
    driver: local
networks:
  logging:
    driver: bridge
