# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('long', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
